# Generated by Django 4.1.2 on 2022-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(to='main_app.exercise'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name='Workout Date'),
        ),
    ]
